import { v4 as uuid } from "uuid";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
  {
    _id: uuid(),
    title: "Black Normal Tees",
    make: "Js Fashion",
    actualPrice: "900",
    discountedPrice: "500",
    categoryName: "normal-tees",
    rating: "3",
  },
  {
    _id: uuid(),
    title: "Black Pullover Hoodies",
    make: "Js Fashion",
    actualPrice: "1200",
    discountedPrice: "400",
    categoryName: "pullover-hoodies",
    rating: "2",
  },
  {
    _id: uuid(),
    title: "Black Stencil Hoodies",
    make: "Js Fashion",
    actualPrice: "1250",
    discountedPrice: "900",
    categoryName: "stencil-hoodies",
    rating: "1",
  },
  {
    _id: uuid(),
    title: "Black Full Sleeve Tees",
    make: "Js Fashion",
    actualPrice: "900",
    discountedPrice: "650",
    categoryName: "full-sleeve-tees",
    rating: "4",
  },
  {
    _id: uuid(),
    title: "Green Normal Tees",
    make: "Js Fashion",
    actualPrice: "800",
    discountedPrice: "300",
    categoryName: "normal-tees",
    rating: "5",
  },
  {
    _id: uuid(),
    title: "Green Pullover Hoodies",
    make: "Js Fashion",
    actualPrice: "800",
    discountedPrice: "450",
    categoryName: "pullover-hoodies",
    rating: "3",
  },
  {
    _id: uuid(),
    title: "Green Stencil Hoodies",
    make: "Js Fashion",
    actualPrice: "1400",
    discountedPrice: "800",
    categoryName: "stencil-hoodies",
    rating: "4",
  },
  {
    _id: uuid(),
    title: "Green Full Sleeve Tees",
    make: "Js Fashion",
    actualPrice: "900",
    discountedPrice: "450",
    categoryName: "full-sleeve-tees",
    rating: "3",
  },
  {
    _id: uuid(),
    title: "Brown Normal Tees",
    make: "Js Fashion",
    actualPrice: "800",
    discountedPrice: "200",
    categoryName: "normal-tees",
    rating: "3.7",
  },
  {
    _id: uuid(),
    title: "Brown Pullover Hoodies",
    make: "Js Fashion",
    actualPrice: "2000",
    discountedPrice: "950",
    categoryName: "pullover-hoodies",
    rating: "4.8",
  },
  {
    _id: uuid(),
    title: "Brown Stencil Hoodies",
    make: "Js Fashion",
    actualPrice: "800",

    discountedPrice: "500",
    categoryName: "stencil-hoodies",
    rating: "4.2",
  },
  {
    _id: uuid(),
    title: "Brown Full Sleeve Tees",
    make: "Js Fashion",
    actualPrice: "850",
    discountedPrice: "350",
    categoryName: "full-sleeve-tees",
    rating: "3.7",
  },
  {
    _id: uuid(),
    title: "Maroon Normal Tees",
    make: "Js Fashion",
    actualPrice: "700",
    discountedPrice: "300",
    categoryName: "normal-tees",
    rating: "3.6",
  },
  {
    _id: uuid(),
    title: "Maroon Pullover Hoodies",
    make: "Js Fashion",
    actualPrice: "1500",
    discountedPrice: "650",
    categoryName: "pullover-hoodies",
    rating: "4.2",
  },
  {
    _id: uuid(),
    title: "Maroon Stencil Hoodies",
    make: "Js Fashion",
    actualPrice: "1800",
    discountedPrice: "900",
    categoryName: "stencil-hoodies",
    rating: "4.2",
  },
  {
    _id: uuid(),
    title: "Maroon Full Sleeve Tees",
    make: "Js Fashion",
    actualPrice: "1200",
    discountedPrice: "650",
    categoryName: "full-sleeve-tees",
    rating: "3.8",
  },
];
