import { v4 as uuid } from "uuid";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
  {
    _id: uuid(),
    title: "Black Normal Tees",
    make: "Js Fashion",
    actualPrice: "900",
    discountedPrice: "500",
    categoryName: "normal-tees",
    imgSrc: "/assets/black-normal-tees.jpg",
    rating: "3",
    id: 1,
  },
  {
    _id: uuid(),
    title: "Black Pullover Hoodies",
    make: "Js Fashion",
    actualPrice: "1200",
    discountedPrice: "400",
    categoryName: "pullover-hoodies",
    imgSrc: "/assets/black-pullover-hoodies.jpg",
    rating: "2",
    id: 2,
  },
  {
    _id: uuid(),
    title: "Black Crewneck Hoodies",
    make: "Js Fashion",
    actualPrice: "1250",
    discountedPrice: "900",
    categoryName: "crewneck-hoodies",
    imgSrc: "/assets/black-crewneck-hoodies.jpg",
    rating: "1",
    id: 3,
  },
  {
    _id: uuid(),
    title: "Black Full Sleeve Tees",
    make: "Js Fashion",
    actualPrice: "900",
    discountedPrice: "650",
    categoryName: "full-sleeve-tees",
    imgSrc: "/assets/black-full-sleeve-tees.jpg",
    rating: "4",
    id: 4,
  },
  {
    _id: uuid(),
    title: "Green Normal Tees",
    make: "Js Fashion",
    actualPrice: "800",
    discountedPrice: "300",
    categoryName: "normal-tees",
    imgSrc: "/assets/green-normal-tees.jpg",
    rating: "5",
    id: 5,
  },
  {
    _id: uuid(),
    title: "Green Pullover Hoodies",
    make: "Js Fashion",
    actualPrice: "800",
    discountedPrice: "450",
    categoryName: "pullover-hoodies",
    imgSrc: "/assets/green-pullover-hoodies.jpg",
    rating: "3",
    id: 6,
  },
  {
    _id: uuid(),
    title: "Green Crewneck Hoodies",
    make: "Js Fashion",
    actualPrice: "1400",
    discountedPrice: "800",
    categoryName: "crewneck-hoodies",
    imgSrc: "/assets/green-crewneck-hoodies.jpg",
    rating: "4",
    id: 7,
  },
  {
    _id: uuid(),
    title: "Green Full Sleeve Tees",
    make: "Js Fashion",
    actualPrice: "900",
    discountedPrice: "450",
    categoryName: "full-sleeve-tees",
    imgSrc: "/assets/green-full-sleeve-tees.jpg",
    rating: "3",
    id: 8,
  },
  {
    _id: uuid(),
    title: "Blue Normal Tees",
    make: "Js Fashion",
    actualPrice: "800",
    discountedPrice: "200",
    categoryName: "normal-tees",
    imgSrc: "/assets/blue-normal-tees.jpg",
    rating: "3.7",
    id: 9,
  },
  {
    _id: uuid(),
    title: "Blue Pullover Hoodies",
    make: "Js Fashion",
    actualPrice: "2000",
    discountedPrice: "950",
    categoryName: "pullover-hoodies",
    imgSrc: "/assets/blue-pullover-hoodies.jpg",
    rating: "4.8",
    id: 10,
  },
  {
    _id: uuid(),
    title: "Blue Crewneck Hoodies",
    make: "Js Fashion",
    actualPrice: "800",
    imgSrc: "/assets/blue-crewneck-hoodies.jpg",
    discountedPrice: "500",
    categoryName: "crewneck-hoodies",
    rating: "4.2",
    id: 11,
  },
  {
    _id: uuid(),
    title: "Blue Full Sleeve Tees",
    make: "Js Fashion",
    actualPrice: "850",
    discountedPrice: "350",
    categoryName: "full-sleeve-tees",
    imgSrc: "/assets/blue-full-sleeve-tees.jpg",
    rating: "3.7",
    id: 12,
  },
  {
    _id: uuid(),
    title: "Maroon Normal Tees",
    make: "Js Fashion",
    actualPrice: "700",
    discountedPrice: "300",
    categoryName: "normal-tees",
    imgSrc: "/assets/maroon-normal-tees.jpg",
    rating: "3.6",
    id: 13,
  },
  {
    _id: uuid(),
    title: "Maroon Pullover Hoodies",
    make: "Js Fashion",
    actualPrice: "1500",
    discountedPrice: "650",
    categoryName: "pullover-hoodies",
    imgSrc: "/assets/maroon-pullover-hoodies.jpg",
    rating: "4.2",
    id: 14,
  },
  {
    _id: uuid(),
    title: "Maroon Crewneck Hoodies",
    make: "Js Fashion",
    actualPrice: "1800",
    discountedPrice: "900",
    categoryName: "crewneck-hoodies",
    imgSrc: "/assets/maroon-crewneck-hoodies.jpg",
    rating: "4.2",
    id: 15,
  },
  {
    _id: uuid(),
    title: "Maroon Full Sleeve Tees",
    make: "Js Fashion",
    actualPrice: "1200",
    discountedPrice: "650",
    categoryName: "full-sleeve-tees",
    imgSrc: "/assets/maroon-full-sleeve-tees.jpg",
    rating: "3.8",
    id: 16,
  },
];
